### ISSUE TITLE
the restfule API doesn‘’t work

### ISSUE THREAD

**Issue by ultimatedaotu** [ddangelov/RESTful-Top2Vec#2]
I start a docker container to see the results of algorithm, but can not attach it, and the container stop itself later.

**Comment by ddangelov** [comment]
Did you follow the instructions here: https://github.com/ddangelov/RESTful-Top2Vec

Could you please provide more details?

**Comment by ultimatedaotu** [comment]
yes I follow this page 
![图片](https://user-images.githubusercontent.com/58505034/92679275-8d36b380-f35a-11ea-82d7-1b6efa6e42f1.png)
![图片](https://user-images.githubusercontent.com/58505034/92679557-4f865a80-f35b-11ea-904a-7734c05f39c8.png)

but the container stop itself several seconds later.

**Comment by ultimatedaotu** [comment]
There is an unlabeled corpus information retrieval task on education research, and I find that the top2vec model can map the latent topics and word vector to semantic space.Maybe that's what I want.

**Comment by ddangelov** [comment]
You need to first train a Top2Vec model: https://github.com/ddangelov/Top2Vec

For the `export model_path='/path_to_top2vec_model'`, the `model_path` has to be to a saved Top2Vec model.
